package com.hmi.alarm.service;

import com.hmi.alarm.entity.Alarm;
import com.hmi.alarm.entity.Severity;
import com.hmi.alarm.repository.AlarmRepository;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Periodically raises a random pre-existing alarm to simulate live plant activity.
 * Implements the "Console: generate random alarms at intervals" requirement.
 */
@Service
public class AlarmGeneratorService {

    private static final Logger log = LoggerFactory.getLogger(AlarmGeneratorService.class);

    private final AlarmRepository alarmRepository;
    private final AlarmService alarmService;

    @Value("${alarm.generator.enabled:true}")
    private boolean enabled;

    public AlarmGeneratorService(AlarmRepository alarmRepository, AlarmService alarmService) {
        this.alarmRepository = alarmRepository;
        this.alarmService = alarmService;
    }

    @PostConstruct
    @Transactional
    public void seedDefaultAlarms() {
        if (alarmRepository.count() > 0) return;

        List<Alarm> defaults = List.of(
                new Alarm("TEMP_HIGH",       "Reactor temperature above safe threshold (>250°C)", Severity.CRITICAL),
                new Alarm("PRESSURE_HIGH",   "Boiler pressure exceeded operational limit",          Severity.HIGH),
                new Alarm("LEVEL_LOW",       "Coolant tank level below minimum",                    Severity.HIGH),
                new Alarm("FLOW_LOW",        "Pump-3 flow rate dropped below setpoint",             Severity.MEDIUM),
                new Alarm("VIB_HIGH",        "Compressor vibration spike detected",                 Severity.MEDIUM),
                new Alarm("MOTOR_OVERLOAD",  "Conveyor motor M-12 overload",                        Severity.HIGH),
                new Alarm("VALVE_FAULT",     "Solenoid valve V-07 stuck",                           Severity.MEDIUM),
                new Alarm("COMM_LOSS",       "PLC communication lost on rack 2",                    Severity.CRITICAL),
                new Alarm("DOOR_OPEN",       "Cabinet door open in control room",                   Severity.LOW),
                new Alarm("FILTER_CLOG",     "Hydraulic filter approaching clog limit",             Severity.LOW),
                new Alarm("BATTERY_LOW",     "UPS battery below 30%",                               Severity.MEDIUM),
                new Alarm("SENSOR_DRIFT",    "Pressure sensor PT-101 drift detected",               Severity.LOW)
        );
        alarmRepository.saveAll(defaults);
        log.info("Seeded {} default alarms", defaults.size());
    }

    @Scheduled(fixedDelayString = "${alarm.generator.interval-ms:15000}")
    public void generateRandomEvent() {
        if (!enabled) return;

        try {
            List<Alarm> all = alarmRepository.findAll();
            if (all.isEmpty()) return;

            Alarm pick = all.get(ThreadLocalRandom.current().nextInt(all.size()));
            // 70% raise, 30% clear, to keep activity flowing
            if (ThreadLocalRandom.current().nextInt(100) < 70) {
                alarmService.raise(pick.getId(), "Auto-generated by simulator");
            } else {
                alarmService.clear(pick.getId(), "Auto-cleared by simulator");
            }
        } catch (Exception e) {
            log.warn("Random event generation failed: {}", e.getMessage());
        }
    }
}
